# Generated by Django 6.0.2 on 2026-02-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True, verbose_name='ID продукта в Stripe')),
                ('price_id', models.CharField(max_length=100, unique=True, verbose_name='ID цены в Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_product', to='lms.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'продукт Stripe',
                'verbose_name_plural': 'продукты Stripe',
            },
        ),
    ]
